# .github/dependabot.yml

# Configuration for Dependabot version updates
version: 2
updates:
  - package-ecosystem: "pip" # Specify the package ecosystem (e.g., pip for Python)
    directory: "/" # Location of package manifests (root directory in this case)
    schedule:
      interval: "weekly" # Frequency for version updates (e.g., daily, weekly, monthly)
    # open-pull-requests-limit: 4 # Limit the number of open pull requests
   # ignore: # List of dependencies to ignore
    #  - dependency-name: "express" # Example of dependency to ignore
     #   versions: ["4.x.x", "5.x.x"]
   # assignees: # Assign people or teams to review the pull requests
   #   - "team-name" # Replace with actual GitHub team name
    labels: # Label for the pull requests Dependabot creates
      - "dependencies update"
      - "automated PR"
    reviewers: # Reviewers for pull requests
      - "grhawkeye"
    commit-message: # Customize the commit message prefix
      prefix: "chore"
      prefix-development: "[Dependabot]"
    versioning-strategy: "increase" # Determines how to increase versions
    allow: # Specify allowed updates
      - dependency-type: "direct" # Only direct dependencies
    # You can add more ecosystems as needed
    # - package-ecosystem: "npm"
    #   directory: "/path/to/directory"
    #   schedule:
    #     interval: "weekly"
    #   labels:
    #     - "npm"
